# Generated by Django 3.2.8 on 2021-10-28 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webdata',
            old_name='socialmedia',
            new_name='socialmedias',
        ),
    ]
