# Generated by Django 3.2.8 on 2021-10-28 07:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211028_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactformdata',
            options={'ordering': ['time']},
        ),
        migrations.AddField(
            model_name='contactformdata',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
