# Generated by Django 3.2.8 on 2021-10-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211028_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactformdata',
            options={},
        ),
        migrations.AlterField(
            model_name='contactformdata',
            name='time',
            field=models.DateTimeField(default=True),
        ),
    ]
