# Generated by Django 3.2.8 on 2021-10-28 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_contactformdata_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactFormData',
        ),
    ]
