# Generated by Django 3.2.8 on 2021-10-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20211028_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformdata',
            name='message',
            field=models.CharField(max_length=1500),
        ),
    ]
